apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: upcommerce-app-two-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upcommerce-app-two
  minReplicas: 1
  maxReplicas: 10  # Set the maximum number of replicas
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Target CPU utilization percentage to trigger scaling
